# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 <Company Name>

{{- $release_name := include "cdn.fullname" . }}

{{- if not .Values.PersistentVolume.rootfs.scratch }}
{{- if not .Values.PersistentVolume.rootfs.imgSrc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cdn.fullname" . }}-dv
spec:
  accessModes:
        - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ required "Rootfs Volume Size required. Missing" .Values.PersistentVolume.rootfs.size }}
  volumeName: {{ template "cdn.fullname" . }}-rootfs-pv0
{{- end }}
{{- end }}
{{- range $cacheDisk, $val := .Values.PersistentVolume.cacheDisks }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $release_name }}-{{ $cacheDisk }}-pvc
spec:
  accessModes:
        - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ $val.size }}
  volumeName: {{ $release_name }}-{{ $cacheDisk }}-pv
{{- end }}

