# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 <Company Name>

apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample_container_chart.fullname" . }}
  labels:
    {{- include "sample_container_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sample_container_chart.selectorLabels" . | nindent 4 }}
