# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 <Company Name>

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample_container_chart.serviceAccountName" . }}
  labels:
    {{- include "sample_container_chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
